In [4]:
import numpy as np

p = np.array([100,80,50])
n = np.array([3,4,5])

np.dot(p,n)

870

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])
C = A @ B
C

array([[22, 28],
       [49, 64]])

In [6]:
C = B @ A
C

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [7]:
A = np.array([[1, 2, 3]])
B = np.array([[4, 7], [5,8], [6,9]])
C = A @ B
C

array([[32, 50]])

In [8]:
C = B @ A
C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 2)

In [10]:
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6], [7,8]])
C = A @ B
C

array([[19, 22],
       [43, 50]])

In [11]:
C = B @ A
C

array([[23, 34],
       [31, 46]])

In [15]:
A = np.array([[1, 2], [3, 4], [5, 6]])
np.dot(A.T, A)

array([[35, 44],
       [44, 56]])

In [16]:
A = np.array([[1], [2], [3]])
np.dot(A.T, A)

array([[14]])

In [17]:
np.dot(A, A.T)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [46]:
from sklearn.datasets import load_iris
X = load_iris().data
a = X.T@X
a

array([[5223.85, 2673.43, 3483.76, 1128.14],
       [2673.43, 1430.4 , 1674.3 ,  531.89],
       [3483.76, 1674.3 , 2582.71,  869.11],
       [1128.14,  531.89,  869.11,  302.33]])